# Generated by Django 4.2.6 on 2023-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, verbose_name='Город')),
                ('temperature', models.FloatField(blank=True, help_text='градусов Цельсия', null=True, verbose_name='Температура')),
                ('pressure', models.FloatField(blank=True, help_text='мм.рт.ст', null=True, verbose_name='Давление')),
                ('wind', models.FloatField(blank=True, help_text='м/с', null=True, verbose_name='Скорость ветра')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Прогноз Погоды',
                'verbose_name_plural': 'Прогнозы Погоды',
            },
        ),
    ]
